/* ============================================================
   DATA-CULTURA.JS — Notas culturales
   ------------------------------------------------------------
   Versión v3 (24/09/2026). Explicaciones cortas sobre cómo se usa el
   idioma en la vida real: cuándo tutear, cómo se dicta un teléfono,
   qué no hacer en un cumpleaños…
   Cada nota:
     id        CUL-xxx, estable
     tipo      Pragmática · Nombres · Rituales · Vida práctica
     nivel     A1…C1 (una nota puede tener más adelante una versión
               más profunda para un nivel mayor)
     titulo, resumen (una o dos líneas, para mostrar en un diálogo),
     texto (la explicación completa, para la hoja a pantalla completa)
     rio       comparación con el Río de la Plata
     ejemplos  [ruso con {palabra}, español, explicación], mismo
               formato que data-gramatica.js
     lex       IDs del léxico de las palabras de las que habla la nota
   Las notas describen costumbres y tendencias, no estereotipos.
   Los diálogos y frases que citan cada nota se calculan en la página.
   ============================================================ */

const CULTURA = [
  {"id":"CUL-001","tipo":"Pragmática","nivel":"A1","titulo":"Ты y вы: cuándo tutear","resumen":"Con amigos, familia y chicos se usa ты. Con desconocidos, gente mayor, en un negocio o en el trabajo, вы. Ante la duda, вы.","texto":"En ruso hay dos formas de hablarle a alguien. Ты es la de confianza: amigos, familia, compañeros de tu edad, chicos. Вы es la de respeto: alguien que no conocés, una persona mayor, un vendedor, un médico, tu profesora o tu jefe. Вы también es el plural: sirve para hablarle a varias personas, las conozcas o no. El paso de вы a ты suele proponerlo la persona mayor o de más jerarquía, a veces con la fórmula «Дава́й на ты». Usar ты con alguien que espera вы suena confianzudo; usar вы con un amigo suena frío o irónico.","rio":"Es parecido a vos y usted, pero en ruso el вы se usa mucho más: con cualquier adulto desconocido, aunque sea joven, y durante bastante tiempo en el trabajo. Nosotros pasamos al vos casi enseguida; en ruso conviene esperar a que te lo propongan.","ejemplos":[["{Ты} говори́шь по-ру́сски?","¿Hablás ruso?","A un amigo: ты, y el verbo en segunda persona del singular."],["{Вы} говори́те по-ру́сски?","¿Habla ruso?","A un desconocido: вы, y el verbo en segunda persona del plural, aunque sea una sola persona."],["{Дава́й на ты}!","¡Tuteémonos!","La fórmula para proponer pasar al ты."]],"lex":["CMR-00033","CMR-00038"]},
  {"id":"CUL-002","tipo":"Pragmática","nivel":"A1","titulo":"«Как дела́?» va en serio","resumen":"No es un saludo automático: quien pregunta espera una respuesta. Lo más común es «Норма́льно» o «Хорошо́», y devolver la pregunta.","texto":"«Как дела́?» se pregunta sobre todo a gente conocida, y se espera una respuesta de verdad, aunque sea corta. Si las cosas van mal, está bien decirlo: «Так себе́» (más o menos) o «Не о́чень». La respuesta más neutra es «Норма́льно», que no significa «normal» sino «bien, sin novedades». A un desconocido no se le pregunta «Как дела́?»: con «Здра́вствуйте» alcanza.","rio":"«¿Todo bien?» o «¿Cómo andás?» casi siempre se contestan «bien» sin pensar. En ruso la pregunta es más personal: no se la hagas a la cajera del súper.","ejemplos":[["Как {дела́}?","¿Cómo andás?","Дела́ es el plural de де́ло, «asunto»: literalmente, «¿cómo van los asuntos?»."],["{Норма́льно}. А у тебя́?","Bien. ¿Y vos?","La respuesta más común y neutra."],["{Так себе́}.","Más o menos.","Una respuesta honesta cuando las cosas no van tan bien."]],"lex":["CMR-00065","CMR-03966"]},
  {"id":"CUL-003","tipo":"Nombres","nivel":"A1","titulo":"Nombre, patronímico y diminutivo","resumen":"Los rusos tienen nombre, patronímico (se forma con el nombre del padre: Петро́вич, Петро́вна) y apellido. Para tratar de вы se usa nombre y patronímico: «О́льга Петро́вна».","texto":"Todo ruso tiene tres nombres: el de pila; el patronímico, que se forma con el nombre del padre (Пётр → Петро́вич para un hombre, Петро́вна para una mujer), y el apellido. Con alguien a quien tratás de вы, como una profesora, un jefe o una persona mayor, se usa el nombre y el patronímico: «О́льга Петро́вна», nunca solo el apellido. Entre amigos se usan diminutivos, que a veces no se parecen al nombre: Мари́я → Ма́ша, Дми́трий → Ди́ма, Алекса́ндр → Са́ша, Евге́ний → Же́ня. El apellido también cambia con el género: Петро́в, Петро́ва.","rio":"Nosotros no tenemos patronímico, y llamar a una profesora por su nombre es normal. En Rusia, un estudiante le dice «О́льга Петро́вна», y ella a él le puede decir simplemente «Лу́кас».","ejemplos":[["Меня́ зову́т {О́льга Петро́вна}.","Me llamo Olga Petrovna.","Nombre y patronímico: su papá se llama Пётр."],["Его́ зову́т {Ди́ма}.","Se llama Dima.","Ди́ма es el diminutivo de Дми́трий. En los documentos dice Дми́трий."]],"lex":["CMR-00239"]},
  {"id":"CUL-004","tipo":"Pragmática","nivel":"A1","titulo":"Пожа́луйста, la palabra comodín","resumen":"Sirve para pedir («por favor»), para responder a un gracias («de nada») y para dar algo («acá tiene»).","texto":"Пожа́луйста tiene tres usos. Al pedir algo es «por favor», y suele ir al final: «Ко́фе, пожа́луйста». Cuando te dan las gracias es «de nada»: «Спаси́бо! — Пожа́луйста!». Y cuando le das algo a alguien es «acá tiene»: «Вот ваш ключ, пожа́луйста». Otra respuesta a спаси́бо es «Не за что» («no hay de qué»). En el habla rápida, пожа́луйста suena casi «pazhálsta».","rio":"En castellano usamos tres expresiones distintas; en ruso alcanza con una. Y se dice mucho: pedir algo sin пожа́луйста suena seco.","ejemplos":[["Ко́фе, {пожа́луйста}.","Un café, por favor.","Para pedir."],["Спаси́бо! — {Пожа́луйста}!","¡Gracias! —¡De nada!","Para responder a un gracias."],["Вот, {пожа́луйста}.","Acá tiene.","Para dar algo."]],"lex":["CMR-01243","CMR-02213"]},
  {"id":"CUL-005","tipo":"Vida práctica","nivel":"A1","titulo":"En el café y el restaurante","resumen":"Para pedir se dice «Я бу́ду…». Al mozo se lo llama con «Извини́те!» o «Молодо́й челове́к!». La propina ronda el 10 %.","texto":"Para pedir comida o bebida, lo más natural es «Я бу́ду…» seguido de lo que querés, en acusativo: «Я бу́ду борщ», «Я бу́ду ко́фе». Para llamar al mozo se usa «Извини́те!», o también «Молодо́й челове́к!» si es un hombre joven y «Де́вушка!» si es una mujer joven, y no es descortés. La cuenta se pide con «Счёт, пожа́луйста». La propina no es obligatoria; si el servicio fue bueno, lo habitual es dejar alrededor del 10 %.","rio":"La propina es parecida a la de Buenos Aires. Lo que cambia es cómo llamar al mozo: decirle «¡joven!» en castellano suena raro, pero «Молодо́й челове́к!» en ruso es lo normal.","ejemplos":[["Я {бу́ду} борщ.","Voy a pedir borsch.","Бу́ду + lo que pedís: la forma más común de pedir."],["{Счёт}, пожа́луйста.","La cuenta, por favor.","Счёт es la cuenta."],["{Молодо́й челове́к}, мо́жно меню́?","Disculpe, ¿me trae la carta?","Literalmente «joven»: así se llama al mozo."]],"lex":["CMR-00241","CMR-00039","CMR-00509","CMR-00431","CMR-04821"]},
  {"id":"CUL-006","tipo":"Rituales","nivel":"A1","titulo":"Cumpleaños: nunca antes de tiempo","resumen":"En Rusia no se saluda por el cumpleaños antes de la fecha: se dice que trae mala suerte.","texto":"Una superstición muy extendida dice que felicitar a alguien antes de su cumpleaños trae mala suerte. Por eso, si te enterás de que es mañana, esperá: «Поздра́вишь за́втра» («me saludás mañana»). Si te olvidaste, felicitar después sí está bien. Otra costumbre: muchas veces el que cumple años es el que invita, por ejemplo con una torta en la oficina. La fórmula es «С днём рожде́ния!», literalmente «¡con el día del nacimiento!».","rio":"Nosotros saludamos a las doce en punto, y adelantarse no es grave. En Rusia, mejor esperá al día.","ejemplos":[["{С днём рожде́ния}!","¡Feliz cumpleaños!","С + instrumental: una fórmula fija, como С Но́вым го́дом! («¡Feliz Año Nuevo!»)."],["Ещё ра́но! {Поздра́вишь} за́втра.","¡Todavía es temprano! Me saludás mañana.","Поздра́вишь es el futuro de поздра́вить, «felicitar»."]],"lex":["CMR-01230","CMR-05117"]},
  {"id":"CUL-007","tipo":"Vida práctica","nivel":"A1","titulo":"Cómo se dicta un teléfono","resumen":"Los números se dictan en grupos: uno de tres cifras y dos de dos. 123-45-67 se dice «сто два́дцать три, со́рок пять, шестьдеся́т семь».","texto":"En Rusia casi nadie dicta un número cifra por cifra. Los siete dígitos finales se agrupan como 123-45-67, y cada grupo se lee como un número entero: «сто два́дцать три — со́рок пять — шестьдеся́т семь». Los celulares tienen once dígitos y empiezan con 8 o con +7, el código de Rusia: 8 916 123-45-67. Si no entendés, pedí «Повтори́те, пожа́луйста».","rio":"Nosotros también dictamos de a grupos, pero el primero en ruso es de tres cifras: para entender un teléfono hay que saber los números hasta 999.","ejemplos":[["{Сто два́дцать три} — со́рок пять — шестьдеся́т семь.","123-45-67","Cada grupo se lee como un número entero."],["Како́й у тебя́ {но́мер} телефо́на?","¿Cuál es tu número de teléfono?","Но́мер телефо́на: «número del teléfono», con телефо́н en genitivo."]],"lex":["CMR-00548","CMR-00676"]},
  {"id":"CUL-008","tipo":"Vida práctica","nivel":"A1","titulo":"Emergencias","resumen":"El número único de emergencias es el 112. La ambulancia es el 103, y en el habla se la llama «ско́рая».","texto":"Desde cualquier teléfono, el 112 comunica con todos los servicios de emergencia. También hay números directos: 101 (bomberos), 102 (policía) y 103 (ambulancia). La ambulancia se llama ско́рая по́мощь, «ayuda rápida», y en el habla se dice solo ско́рая: «Вы́зовите ско́рую!».","rio":"Es como el 911: el número que conviene memorizar es el 112, que también funciona desde un celular extranjero.","ejemplos":[["{Вы́зовите} ско́рую!","¡Llame a una ambulancia!","Imperativo de вы́звать, con вы."],["Челове́ку {пло́хо}!","¡Alguien se siente mal!","A quién le pasa va en dativo: челове́ку, «a una persona»."],["{Помоги́те}!","¡Ayuda!","Imperativo de помо́чь con вы: sirve para pedir ayuda a cualquiera."]],"lex":["CMR-00338","CMR-00750","CMR-00497"]},
  {"id":"CUL-009","tipo":"Pragmática","nivel":"A1","titulo":"Hablarle a un desconocido","resumen":"Para preguntar algo en la calle se empieza con «Извини́те» o «Скажи́те, пожа́луйста», y se usa siempre вы.","texto":"Para frenar a alguien en la calle y preguntarle algo, lo normal es arrancar con «Извини́те» («disculpe») o «Скажи́те, пожа́луйста» («dígame, por favor»), y después hacer la pregunta: «Скажи́те, пожа́луйста, где метро́?». Siempre con вы. Las respuestas pueden sonar cortantes («Пря́мо», «Не зна́ю»), pero no suele ser falta de amabilidad: se contesta lo justo. El «спаси́бо» al final nunca falta.","rio":"Nosotros solemos arrancar con un «¡Hola! Perdón, una pregunta…». En ruso no hace falta el hola: «Извини́те» ya abre la conversación.","ejemplos":[["{Извини́те}, где вокза́л?","Disculpe, ¿dónde queda la estación?","Извини́те abre la conversación, como «disculpe»."],["{Скажи́те}, пожа́луйста, как дое́хать до це́нтра?","Disculpe, ¿cómo llego al centro?","Literalmente, «dígame, por favor»."]],"lex":["CMR-01992","CMR-00042"]}
];

function culturaById(id) { return CULTURA.find(c => c.id === id) || null; }
/* Notas que hablan de una palabra del léxico (para la ficha). */
function culturaDePalabra(lexId) { return CULTURA.filter(c => (c.lex || []).indexOf(lexId) >= 0); }
if (typeof window !== "undefined") { window.culturaById = culturaById; window.culturaDePalabra = culturaDePalabra; }
